### PR TITLE
Adjusted BMI

### PR DESCRIPTION
**Pull request by kittychenn**
Adjusted BMI function and documentation added to BMI.R, in which BMI calculation uses correction value based on sex. HWTGCOR (2015+) and HWTGCOR_der (all cycle) were also added. 

Adjustment obtained from (pg83 in pdf): https://osf.io/ycxaq/

### CODE REVIEW

**Review by DougManuel — COMMENTED** [review]
An aside, the derived BMI categories are well described on page 65 of the documentation and could be added if we don't have them yet in cchsflow. @kittychenn

**Review by wyusuf068 — APPROVED** [review]
Looks good. Great job @kittychenn!

**Comment by kittychenn** [comment]
@DougManuel The Cole's classification for age 12-17 (`HWTDVCOL`) or international standard for age 18+ (`HWTDGISW`)? I'll be using the international one for the current categorization but I can definitely include Cole's later.

**Comment by DougManuel** [comment]
> @DougManuel The Cole's classification for age 12-17 (`HWTDVCOL`) or international standard for age 18+ (`HWTDGISW`)? I'll be using the international one for the current categorization but I can definitely include Cole's later.

Yes. Later.

**Pull request merged**
