### PR TITLE
New categorical age, depression, and influenza variables

### PR DESCRIPTION
**Pull request by wyusuf068**
Breaking changes:

- Notation in **recFrom** column of `variable_details.csv` changed to interval notation (e.g. 7:9 is now denoted as [7,9]).
- New **description** column in `variables.csv`
- New **role** column in `variables.csv` 

New variables added:

- Age:
1. DHHGAGE_5: age variable categorized into 5 20-year age groups
2. DHHGAGE_D: age variable categorized into 8 10-year age groups

- Depression:
1. DPSDPP: Depression Scale - Predicted Probability
2. DPSDSF: Depression Scale - Short Form Score
3. DIS_10G: Frequency - distress: felt sad / depressed - past month
4. DIS_10H: Frequency - distress: depressed/nothing cheers - past month
5. DPSDMT: Specific month when felt depressed
6. DPSDWK: Number of weeks felt depressed - (D)
7. DPS_02: Felt sad/blue/depressed - 2 weeks or more - 12 mo
8. DPS_03: Sad/depressed - length feelings lasted - 2 wk
9. DPS_04: Sad/depressed - frequency - 2 wk
10. DPS_05: Sad/depressed - lose interest in things - 2 wk
11. DPS_06: Sad/depressed - felt tired out / low on energy - 2 wk
12. DPS_07: Sad/depressed - weight change - 2 wk
13. DPS_08A: Sad/depressed - weight change (amount) - 2 wk
14. DPS_08B: Sad/depressed - weight change (lb/kg) - 2 wk
15. DPS_09: Sad/depressed - trouble falling asleep - 2 wk
16. DPS_10: Sad/depressed trouble falling asleep - frequency - 2 wk
17. DPS_11: Sad/depressed - trouble concentrating - 2 wk
18. DPS_12: Sad/depressed - felt down on self - 2 wk
19. DPS_13: Sad/depressed - thought a lot about death - 2 wk
20. DPS_14: Sad/depressed - number of weeks - 12 mo

- Influenza:
1. FLU_160: Ever had a flu shot
2. FLU_162: Last time had flu shot

### CODE REVIEW

**Comment by DougManuel** [comment]
Update NEWS.md to reflect changes in this repo

**Comment by DarkShadeKnigh** [comment]
@DougManuel @wyusuf068 @yulric rec_with_table containing support for intervals is up

**Comment by DougManuel** [comment]
DPSDSF - Isn't this a categorical variable. Suggest a bit more description in `variableStartLabel` and `catLabelLong` that is excerpted from the documentation. 

>1 ) Derived Depression Scale - Short Form Score
DPSDSF
DPS_02, DPS_05, DPS_06, DPS_08A, DPS_08B, DPS_10, DPS_11, DPS_12, DPS_13, DPS_16, DPS_17, DPS_18,
DPS_19, DPS_21A, DPS_21B, DPS_23, DPS_24, DPS_25, DPS_26
This variable assesses the depression level of respondents who felt depressed or lost interest in things for 2 weeks or more
last year. These include normal periods of sadness (for example, after the death of a loved one), as well as "serious"
depression.
The items used to measure depression are based on the work of Kessler and Mroczek (from University of Michigan). They
selected a subset of items from the Composite International Diagnostic Interview (CIDI) that measure major depressive
episodes (MDE). The CIDI is a structure diagnostic instrument that was designed to produce diagnoses according to the
definitions and the criteria of both DSM-lll-R and the Diagnostic Criteria for the Research of the ICD-10. The short-form of
MDE used in the CCHS was developed to operationalize Criteria A through C of the DSM-III-R diagnosis of MDE. The
diagnostic hierarchy rules defined in the Criterion D (not superimposed on schizophrenia, schizophrenia form disorder,
delusional disorders, or psychotic disorders NOS) were ignored.
Higher scores indicate higher level of depression.
National Comorbidity Survey: www.hcp.med.harvard.edu/ncs/
Composite International Diagnostic Interview (CIDI): www.who.int/msa/cidi/index.htm
Variable name:
Based on:
Description:
Note:
Internet site:
Value Condition(s) Description Notes
Specifications
96 DODEP = 2 Module not selected NA
99 ADM_PRX = 1 Module not asked - proxy interview NS
99 (DPST02 = DK, R, NS) or
(DPST05 = DK, R, NS) or
(DPST06 = DK, R, NS) or
(DPST08A = DK, R, NS) or
(DPST10 = DK, R, NS) or
(DPST11 = DK, R, NS) or
(DPST12 = DK, R, NS) or
(DPST13 = DK, R, NS) or
(DPST16 = DK, R, NS) or
(DPS_17 = DK, R, NS) or
(DPS_18 = DK, R, NS) or
(DPST19 = DK, R, NS) or
(DPST21A = DK, R, NS) or
(DPST23 = DK, R, NS) or
(DPST24 = DK, R, NS) or
(DPST25 = DK, R, NS) or
(DPST26 = DK, R, NS)
At least one required question was not answered NS
(don’t know, refusal, not stated)
0 DPST02 < NA and
DPST05 = NA and
DPST19 = NA
Did not feel depressed or did not lose interest in
things for two weeks last year, or did so only mildly
(less than most of day and at least almost everyday
for at least two weeks)
DPST02 +
DPST05 +
DPST06 +
DPST08A +
DPST10 +
DPST11 +
DPST12 +
DPST13
DPST02 = 1 and
(DPST05 = 1, 0) and
(DPST06 = 1, 0) and
(DPST08A = 1, 0) and
(DPST10 = 1, 0) and
(DPST11 = 1, 0) and
(DPST12 = 1, 0) a

**Review by DougManuel — CHANGES_REQUESTED** [review]
1) Few comments for DPSDSF.
2) Update NEWS.md
3) Update documentation for the new interval approach.

**Comment by wyusuf068** [comment]
@DougManuel DPSDSF is considered a continuous variable from 0 to 8 in CCHS documentation. DPSDPP, however, is considered a categorical variable in CCHS documentation. Since the categories in DPSDPP are numeric values, we had decided to specify it as a continuous variable from 0 to 0.90. I will create .R scripts for these two variables elaborating more on how these variables were derived and why they were specified as continuous variables.

**Review by DarkShadeKnigh — APPROVED** [review]

**Pull request merged**
